{
  "uid" : "356817c0446bb5e9",
  "name" : "test_data_source_ops",
  "fullName" : "test_collection_phase.test_data_source_ops",
  "historyId" : "14e1047d5f5a62be35be4b1e8cff8a6",
  "time" : {
    "start" : 1579407934056,
    "stop" : 1579407934056,
    "duration" : 0
  },
  "description" : "This is the tests collection phase. Failures are modules that failed to collect.",
  "descriptionHtml" : "<p>This is the tests collection phase. Failures are modules that failed to collect.</p>\n",
  "status" : "broken",
  "statusMessage" : "failed",
  "statusTrace" : "ImportError while importing test module '/Users/zhumeng/Documents/apm_test/apm_interface_test/testcases/test_data_source_ops.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\ntestcases/test_data_source_ops.py:11: in <module>\n    from apm_modules.template_mgt_ops import TemplateMgtOps\nE   ModuleNotFoundError: No module named 'apm_modules.template_mgt_ops'",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Collection phase"
  }, {
    "name" : "testClass",
    "value" : "test_collection_phase"
  }, {
    "name" : "testMethod",
    "value" : "test_data_source_ops"
  }, {
    "name" : "package",
    "value" : "test_collection_phase"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "356817c0446bb5e9.json",
  "parameterValues" : [ ]
}